version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment: 
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 54323:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data